### ISSUE TITLE
[prosEO CLI] UX: Potitional parameters and Subcommands being empty in the help page

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#10]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
Positional parameters and subcommands are empty. This could mean that indeed there are none but it could also infer not yet written/documented.

**Example output:**
prosEO> help -h
Show the prosEO Command Line Interface help information (this page; for subcommand help, type "<subcommand> --help")
Options:
    -h, --help        Show help information for the current command level (top level commands, when called from the shell command line)
Positional parameters:
Subcommands:
prosEO>

**Further information:**
The CLI should include an output message indicating that the specific command has no associated positional parameters/subcommands when there are indeed none associated.

**Comment by tangobravo62** [comment]
Fixed:
```
prosEO> help -h
Show the prosEO Command Line Interface help information (this page; for subcommand help, type "<subcommand> --help")
Options:
    -h, --help        Show help information for the current command level (top level commands, when called from the shell command line)
Positional parameters:
    -- none --
Subcommands:
    -- none --
```
