### ISSUE TITLE
Production Planner does not propagate processing mode down the processing chain

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#108]
When creating job steps for pre-products, the processing mode given in the order is not propagated to the respective job steps. In the attached screenshot, L2__HCHO__ and L2__CLOUD_ are the requested output products and job steps for the required pre-products L2__AAI___ and L2__CLOUD_ have been generated without processing mode. Had the job step for the "pre-product" L2__CLOUD_ received the correct processing mode, it would not have been generated at all, because then it would have been fulfilled by the job step for the requested output product!

Workaround: Cancel erroneous job steps for L2__CLOUD_ and L2__AAI___ via the CLI. Create the L2__AAI___ pre-product with a separate order.

<img width="1566" alt="Bildschirmfoto 2020-09-24 um 08 57 50" src="https://user-images.githubusercontent.com/29191859/94111807-d7349480-fe44-11ea-874e-46907d607994.png">

**Comment by emelchinger** [comment]
Fixed with changes in planning algorithm.

**Comment by tangobravo62** [comment]
Fixed:
<img width="693" alt="Bildschirmfoto 2021-04-28 um 17 02 12" src="https://user-images.githubusercontent.com/29191859/116426663-991caa80-a843-11eb-944a-d6b9b1d3e563.png">
