### ISSUE TITLE
[prosEO CLI] UX: Documentation is ambiguous - command 'login'

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#11]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
The help documentation ('help') for the command 'login' is a bit ambiguous. It could infer that all commands are valid to be used with login apart from 'mission show'.

**Example output:**
login             Log in to a mission in prosEO. A login is required prior to executing any other command except "mission show".

**Further information:**
A potential enhancement would be to write _"any valid command except..."_

**Comment by tangobravo62** [comment]
Help text reworded:
```
prosEO> login -h
Log in to a mission in prosEO. All valid commands except for "mission show" require prior login.
[...]
```
