### ISSUE TITLE
[prosEO CLI] Confusing error message

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#110]
prosEO version : 0.5.2

**Context**
The following test case produced an error message that is confusing

**Test case**
While being logged in to a mission, the user tries to create a new mission (while knowing that this is not allowed). 
Assumptions/facts:
- The user is not an administrator
- the user is already logged in to an existing mission
- a mission cannot be created by another mission

**Output**
As per the output shown here, the error message is confusing, mentioning that the user cannot manage missions for a mission.
`
prosEO (NM4T)> mission create
Checking for missing mandatory attributes ...
Mission name (empty field cancels): NM4D
Product file name template (empty field cancels): filename.template
(E2803) User NM4T-NM4Tuser1 not authorized to manage missions for mission NM4T
`

**Proposition**
Assuming that the correct message is returned above and this is not a bug, the error message should change to "...is not allowed to create missions as per the user privileges"

**Comment by tangobravo62** [comment]
Fixed. The message now clearly states the conditions as described above:
```
prosEO (PTM)> mission create
(E2784) Operation not allowed, when already logged in to a mission (currently logged in to PTM)
```
