### ISSUE TITLE
[prosEO CLI] Orbit show + range enhancement

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#112]
prosEO version 0.5.2
Windows 10

Context:
When the user is trying to show orbits for a given orbit range and the value of [from] is bigger than the value of [to] the system returns an empty value. While technically correct, it would be a good idea to return an error message that the input was incorrect and that the system should instead use correct lower and upper bounds.

Problematic example:
prosEO (NM4T)> orbit show --from=3003 --to=1234 NM4T_Spacecraft_1
--- []

**Comment by tangobravo62** [comment]
This behaviour is consistent throughout the CLI. However, the messages have been improved somewhat:
```
prosEO (PTM)> orbit show --from=3007 --to=3001 PTS
(E2852) No orbits found for given search criteria
prosEO (PTM)> 
prosEO (PTM)> order show --from=2020-12-31 --to=2020-01-01
(E2930) No orders found for given search criteria
```
Since the CLI aims at proficient users, it is suggested to leave the behaviour as is.

**Comment by tangobravo62** [comment]
No further optimization required.
