### ISSUE TITLE
[prosEO CLI] UX: CTRL+C exits without asking user validation or providing information on what happened

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#12]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
If a user utilizes CTRL+C by accident, the CLI is terminated and the user does not know what was the reason. There is no prompt to indicate to the user what happened, what are the results of the termination of the CLI, if previous work was lost, etc. CTRL+C is an actionable shortcut used in a operating system terminal, for example, but prosEO represents a different user experience environment and has a different scope. As such, a message/prompt could prove beneficial to the users of the prosEO CLI.

**Comment by tangobravo62** [comment]
This is standard behaviour for command-line programs. Typing Ctrl-C is meant to immediately cancel the running program. This is exactly what the CLI does (also when a long running command is being executed).
