### ISSUE TITLE
BaseWrapper: Cleanup products downloaded from or created in file cache

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#121]
Currently the BaseWrapper triggers product downloads from the Storage Manager to the file cache, and it creates output products in the file cache. After completion of the BaseWrapper run these files are not needed any more and shall be cleaned up (principle: whoever creates a resource is responsible for cleanup, as soon as the resource is not needed any more).

**Comment by emelchinger** [comment]
Remove all directories created by base wrapper after ingest of products.

**Comment by emelchinger** [comment]
The directories created by base wrapper were deleted recursive after success or error.

**Comment by tangobravo62** [comment]
Verified and OK.
