### ISSUE TITLE
[prosEO CLI] Cancelled login still requires password

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#14]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
When the user executes the command login without defining a username, a prompt asks the user to input the username. If the user uses ENTER without writing the username first, there is an error message that cancels the login but a password is still requested nonetheless. This implies that the null user is taken as input after the cancelled login and a password for the null user is requested. This could be a cause of security concern but from the user's safety/security point of view but also the user experience point of view.

**Example output:**
prosEO> login ptm
Username:
(I2824) No username given, login cancelled
Password for user :

**Further information:**
There is no indication of how to cancel a login. This could be an enhancement.

**Comment by tangobravo62** [comment]
Fixed:
```
prosEO> login PTM
Username (empty field cancels): 
(I2824) No username given, login cancelled
prosEO> 
```
