### ISSUE TITLE
GUI: Reset job step start and end times at "Reset" (or "Release"/"Resume")

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#147]
If a job step is reset, its start and end times from the last run stay visible. This is especially confusing after the job step has been re-started, so the start time is then seemingly after the end time.

The start/end times and the log shall be reset in the data and in the GUI at a suitable point in the life cycle (at the latest when the job step changes into the "RUNNING" state again).

**Comment by emelchinger** [comment]
start time, completion time, log output and job order file name of a job step are reset during "retry" and "suspend forced" if job step state is not COMPLETED.

**Comment by tangobravo62** [comment]
Tested successfully and used extensively during the S5P DDS6 reprocessing campaign .
