### ISSUE TITLE
[prosEO CLI] Command login should verify the username and mission

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#15]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
When the user chooses to login to a mission, the user is prompted to input the password and system informs the user that it needs the password for a specific username, the one it was used for the login. At the same time, the system does not verify to the user that the login is done for a specific mission as per their request.

**Example output:**
prosEO> login -uuser1 ptm
Password for user user1:

**Further information:**
The output could be: _Password for user user1 in mission ptm_
It could be even more beneficial if the mission is stated explicitly: _Password for user user1 in mission ExampleMission1_

**Comment by tangobravo62** [comment]
Mentioning the mission in the password prompt would suggest a mission-specific password, but passwords are not meant to be mission-specific.
@dlr-tangosierra : If you agree, please close the issue

**Comment by tangobravo62** [comment]
A solution for this issue might also be given in issue #52 (mission as part of command prompt).

**Comment by dlr-tangosierra** [comment]
The idea mentioned in issue #52 is a good one.

**Comment by tangobravo62** [comment]
Resolved with resolution of issue #52
