### ISSUE TITLE
Production Planner: Changes implied by data model v1.4

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#154]
Some attributes have been added in the data model v1.4. For these attributes to be evaluated, the following changes need to be made to the Production Planner:

- Compute evictionTime: When generating new output products, the evictionTime shall be computed as generationTime + productRetentionPeriod, where the productRetentionPeriod is taken from the current processing order, or if that is null, from the mission. If no productRetentionPeriod can be found, the evictionTime remains null (meaning product will not be evicted automatically).
- Add resource requests to Kubernetes scheduling: From the Task object, take the attributes numberOfCpus and minMemory (if set) and in the pod specification create container resource requests for "memory" and "cpu", respectively (as per https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/).
- Allow more than one job to be run on a Kubernetes worker node. The allowed load factor is now configured in ProcessingFacility::maxJobsPerNode (default is 1).

**Comment by emelchinger** [comment]
Implemented and locally tested.

1. As expected
2. The resource requests are sent to Kubernetes:
```
                    resources: class V1ResourceRequirements {
                        limits: null
                        requests: {memory=Quantity{number=1073741824, format=BINARY_SI}, ephemeral-storage=Quantity{number=1073741824, format=BINARY_SI}, cpu=Quantity{number=1, format=DECIMAL_SI}}
                    }

```
3. Kubernetes does the balancing of of jobs and nodes itself. The number of jobs created by the planner is now: nodeCount * maxJobsPerNode

**Comment by tangobravo62** [comment]
Verified and OK.
