### ISSUE TITLE
[prosEO CLI] Option -u : enhancement of the 'help' documentation and user login in general

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#16]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
When reading the help documentation for option -u, information is presented to the user that might prove confusing not only based on what is written but also of what this information might infer from a security point of view.

**Extract from the help:**
-u, --user        The user name for login to prosEO. _If a command is given upon program invocation, but no username, login is attempted using the default user name and password stored in the application configuration file_.

**Further information:**
The users expect to login based on their own username and password credentials. They do not expect to see a default username/password that the system automatically tries to use. Moreover, it is implied that this username/password is saved somewhere, in a configuration file, and from a distant point of view it is seems to be a sort of a master username/password that the system automatically reverts to. This could be a security concern but also problematic from the UX point of view.

Real world example: what is happening when a user tries login to an online website with their account, e.g. on GitHub?

**Comment by tangobravo62** [comment]
Fixed: The comment has been changed to not suggest that a default user from the configuration file will be used in case of no login:
```
Options for the 'proseo' command:
    -v, --version     Show the prosEO CLI version and exit (only for call from shell command line)
    -u, --user        The user name for login to prosEO.
    -p, --password    The password for login to prosEO (only valid if a user name for login is given).
    -m, --mission     The mission to login to (only valid if a user name for login is given)
```
The code was corrected to actually honour the login parameters (was not the case so far).
