### ISSUE TITLE
GUI: Jump to correct page in order display from job step link in Dashboard

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#168]
When clicking on a job step link in the Dashboard, currently the first page of the related processing order is displayed. For large orders spanning several pages this makes for tedious paging, until the correct page is found.

It is requested to change the behaviour so that the correct page containing the job step in question is displayed immediately, when a job step link is clicked in the Dashboard.

**Comment by emelchinger** [comment]
This is implemented.
