### ISSUE TITLE
Unit Tests: Replace external with embedded database

### ISSUE THREAD

**Issue by katharinabassler** [dlr-eoc/prosEO#177]
Where applicable, JUnit tests should be revised to rely on an embedded H2 rather than an external database.

In result, the tests are expected to run faster, and test results are consistent and not affected by external factors, as the database runs in-memory. Additionally, testing on different environments is possible without additional setup and configuration, and tests can be run without affecting any production data.

**Comment by katharinabassler** [comment]
This issue will be addressed together with #119.

**Comment by tangobravo62** [comment]
All unit tests now work from the embedded H2 database as expected. Issue closed.
