### ISSUE TITLE
[prosEO CLI] UX: Enhancement of the documentation for subcommand mission>show 

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#18]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
The documentation for the subcommand mission>show might be a bit confusing. It indicates that the user can invoke information for other missions and processor classes. What could be beneficial is the addition of an example or syntax of how this can be done.

**Extract from the help:**
show              Show all configurations for the current mission and processor class or a named one

**Further information:**
Apart from adding a specific example on how to retrieve information for other missions/processor classes, the actual text could be re-written: _Show all configurations for the current mission and processor class. The user can also define to show all the configurations for other missions/processor classes with the syntax … For example:_

**Comment by tangobravo62** [comment]
@dlr-tangosierra : Could you please give an example (context) of what you received in the help message and what you would have expected?

**Comment by dlr-tangosierra** [comment]
This issue is no longer valid. The "help" documentation has changed. As such I am closing the issue.
