### ISSUE TITLE
[prosEO CLI] UX: Documentation seems to be missing for subcommand configuration > delete

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#19]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
The documentation seems to be missing some information on the required inputs for the subcommand configuration > delete. ClassName and ConfigurationVersion are not mentioned in the 'help' documentation. Moreover, an example could prove to be a welcome addition for the users of the CLI, from the UX point of view.

**Extract from the 'help':**
delete            Remove a configuration from the current mission and processor class

**Example output:**
prosEO> configuration delete
(E2918) Required parameter className not found for command delete
prosEO> configuration delete abc
(E2918) Required parameter configurationVersion not found for command delete
prosEO> configuration delete abc 1
(E2802) User not logged in
(E2803) User null not authorized to manage configurations for mission null
prosEO>

**Comment by tangobravo62** [comment]
Documentation for "configuration delete" command (and other "delete" commands) fixed. Note that for "configuration delete" a login is required:
```
prosEO> configuration delete --help
(E2802) User not logged in

prosEO> login S5P
Username (empty field cancels): proseo
Password for user proseo: 
(I2821) User proseo logged in

prosEO> configuration delete --help
Remove a configuration from the current mission and processor class
Options:
    -h, --help        Show help information for the current command level (top level commands, when called from the shell command line)
Positional parameters:
    className         The name of the processor class
    configurationVersion  The version of the configuration to delete
Subcommands:
    -- none --
```
