### ISSUE TITLE
Archive-Mgr: SIMPLEAIP not available at archive creation

### ISSUE THREAD

**Issue by katharinabassler** [dlr-eoc/prosEO#204]
When creating a new archive with the CLI by specifying a JSON input file, setting the archive type to SIMPLEAIP leads to an error. 

Workaround: However, setting the archive type to AIP and then using the update functionality to modify the type to SIMPLEAIP works.

**Comment by emelchinger** [comment]
Implemented

**Comment by katharinabassler** [comment]
Implementation tested successfully.
