### ISSUE TITLE
[prosEO CLI] UX: There is a command configuration and a subcommand processor>configuration

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#21]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
The system includes the command 'configuration' which is about "Commands for managing configurations" and it also include the subcommand processor>configuration which is about "Commands to manage configured processors". This could be a cause of confusion. 

**Further information:**
Could the command 'configuration' be renamed or the documentation be updated to include some more information on what those configurations are?

**Comment by tangobravo62** [comment]
@dlr-tangosierra : Which "configuration" command should be renamed? Note that the prosEO data model contains a "Configuration" class, which is managed using the "configuration xxx" commands, and a "ConfiguredProcessor" class, which is managed using the "processor configuration xxx" commands.
What alternative name would you suggest?

**Comment by dlr-tangosierra** [comment]
I would say that the name for the "configuration" class might need to be changed but it is not easy to choose a correct alternative. 

Can we update the documentation?

**Currently**
configuration     Commands for managing configurations

**Proposal**
configuration     Commands for managing configurations _of the current mission and processor class or another._ 

And in the sub-command help level:
prosEO> configuration -h
Commands for managing configurations _of the current mission and processor class or another. The sub-commands update,create,delete are restricted only to the current mission and processor class._

**Comment by tangobravo62** [comment]
Documentation updated as requested:
```
prosEO (no mission)> help
[...]
    processor         Commands for managing processor classes, processors, configurations and configured processors
    configuration     Commands for managing configurations of a specific processor class
[...]

prosEO (no mission)> configuration -h
Commands for managing configurations of a specific processor class
Options:
    -h, --help        Show help information for the current command/subcommand level (top level commands, when called from the shell command line)
Positional parameters:
    -- none --
Subcommands:
    show              Show all configurations for the current mission and optionally the given processor class and configuration version
    create            Create a new configuration for the given processor class in the current mission; the user will be prompted for mandatory attributes not given on the command line
    update            Update a configuration for the given processor class in the current mission; the user will be prompted for mandatory attributes not given on the command line
    delete            Remove a configuration from the given processor class in the current mission

prosEO (PTM)> processor configuration -h
Commands to manage configured processors (combinations of processor versions and processor class configurations)
Options:
    -h, --help        Show help information for the current command/subcommand level (top level commands, when called from the shell command line)
Positional parameters:
    -- none --
Subcommands:
    show              Show all configured processors for the current mission or only the one identified
    create            Create a new configured processor by combining a processor version and a (processor class) configuration; the user will be prompted for mandatory attributes not given on the command line
    update            Update a configured processor; the user will be prompted for mandatory attributes not given on the command line
    delete            Delete a configured processor
```
