### ISSUE TITLE
Production Planner: Parameterize sorting of job step queue

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#210]
Currently job steps in "READY" state are sorted by order priority, then ascending sensing start time. While this approach is useful in most Systematic Production and Reprocessing scenarios, ordering by sensing time does not make sense in an On-demand Production scenario.

A new configuration parameter shall be introduced to the Production Planner, where the sorting (after order priority) can be selected as:
- by sensing start time (current approach)
- by order submission time (effectively resulting in a prioritized FIFO job step queue)

TBD which of the two shall be the default value.

**Comment by emelchinger** [comment]
New parameter 'jobStepSort' implemented:
        # Sort mode to start job steps (sensingTime | submissionTime)
        jobStepSort: sensingTime

**Comment by tangobravo62** [comment]
Tested in CDSE environment.
