### ISSUE TITLE
Using proseo CLI commond

### ISSUE THREAD

**Issue by littlehell** [dlr-eoc/prosEO#219]
Hello,

I'm new for ProsEO and just finished compile on Windows 10, I think it already successed like this:
![20240710101009](https://github.com/dlr-eoc/prosEO/assets/28342278/c736e76d-a701-4161-bc17-a49f98ef5362)

From prosEO UI Command Line Interface Syntax, there should be a prosEO excutable file but I searched everwhere I cannot find it.

Is there any error during my compile? Sincerely hope for your help, thanks.

Btw, could ProsEO process CADU data from polar-orbit satllite such as Aqua, NPP and JPSS?

**Comment by tangobravo62** [comment]
Thank you for pointing out this mistake in the CLI syntax description. Actually, there is no executable for the CLI, it is created as a Java JAR archive, and must be started as such: `java -jar proseo-ui-cli.jar`. In the sense of what is meant in the syntax description, the whole sequence must be thought of as the "executable".

For further guidance on how to use prosEO, please refer to the [prosEO Wiki](https://github.com/dlr-eoc/prosEO/wiki).

Regarding CADU processing: Please note that for any real processings, you will need a data processor either written by yourself or provided by a third party. prosEO only acts as an orchestration framework to start data processors, provide them with the necessary input and to handle the processor output. Having said that, processors for CADU processing have indeed already been integrated successfully into prosEO (but this is proprietary code, which is not publicly available).

**Comment by tangobravo62** [comment]
Misleading comment fixed, fix will be part of prosEO 1.1.0.
