### ISSUE TITLE
[prosEO CLI] Command ingest: its usage terminates the CLI

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#22]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
Trying out the command ingest resulted into the termination of the CLI. Please refer to the example output.

**Example output:**
prosEO> ingest -fabc
(E2918) Required parameter processingFacility not found for command ingest
prosEO> ingest -fabc abc
(E2802) User not logged in
prosEO Command Line Interface terminated by exception!

**Comment by tangobravo62** [comment]
Default values for file format fixed throughout CLI. Command now returns with expected error message:
```
prosEO> ingest -fabc abc
(E2806) Command failed (cause: abc (No such file or directory))
```
