### ISSUE TITLE
[prosEO CLI] UX: Documentation missing for the usage of -h // Duplicate to issue #19

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#23]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
Executing 'orbit update' indicates that more information is needed as input. This information might not be very well documented in the 'help'.

**Example output:**
prosEO> orbit update
(E2802) User not logged in
(E2853) Spacecraft code and/or orbit number missing
prosEO> orbit update abc
(E2802) User not logged in
(E2853) Spacecraft code and/or orbit number missing
prosEO> orbit update abc 10
(E2802) User not logged in
(E2803) User null not authorized to manage orbits for mission null

**Extract from the help:**
prosEO> orbit -h
Commands for managing orbits for a given spacecraft
Options:
    -h, --help        Show help information for the current command level (top level commands, when called from the shell command line)

**UX Enhancement:**
Restructure information in 'help' so that the inputs 'command -h' and 'command subcommand -h' are both more visible to the users as valid inputs. While it is written in the command section that -h can be used with the commands, it is easy to be missed that this can also be used on the sub-command level.

**Comment by tangobravo62** [comment]
Clarified that "-h"/"--help" is also available for subcommands:
```
Options for all commands:
    -h, --help        Show help information for the current command/subcommand level (top level commands, when called from the shell command line)
```
