### ISSUE TITLE
[prosEO CLI] Wrong command terminates the command line interface

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#26]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
The command [mission -h spacecraft] returns an exception and terminates the interface.

**Example output:**
prosEO> mission -h spacecraft
prosEO Command Line Interface terminated by exception!

**Comment by tangobravo62** [comment]
Fixed:
```
prosEO> mission -h spacecraft
(E2914) Too many parameters for command mission
prosEO> 
```
