### ISSUE TITLE
[prosEO CLI] {Mission show -h} does not return the help page

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#27]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
It seems that the user needs to be logged in before the help page for the command [mission show -h], which requires login, can be displayed. This could be problematic for some users, if they wanted to understand what this command does. [Mission show -h] functions, on the contrary, so this behavior should be universal. Finally, based on the current output, the user cannot understand what could be missing from the command to show the help page, so the documentation could be updated to reflect its usage.

**Example output:**
prosEO> mission spacecraft -h
(E2802) User not logged in
(E2801) Subcommand missing for command mission

Mission show works on the other hand:
prosEO> mission show -h
(E2802) User not logged in
List all configured missions or only the given one
Options:
...

**Comment by tangobravo62** [comment]
Fixed:
```
prosEO> mission spacecraft -h
(E2802) User not logged in
prosEO> mission show -h
List all configured missions or only the given one
Options:
        --format      The output format (one of { JSON, XML, YAML }; default value YAML [human readable])
    -h, --help        Show help information for the current command level (top level commands, when called from the shell command line)
Positional parameters:
    missionCode       The code of the mission to list
Subcommands:
    -- none --
prosEO> 
```
