### ISSUE TITLE
[prosEO CLI] Null user and commands which require login

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#28]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
When the user tries a command which requires login, [mission show] in this case, the error messages show that the user is not logged in which is a normal output message but as a second message the system shows to the user that it tries to revert to a null user for privileges. From the system design point of view, this could be a security concern, in case by mistake the null user gains such privileges. The nature of this error message causes confusion as well and is a security concern by itself.

**Example output:**
prosEO> mission show
(E2802) User not logged in
(E2803) User null not authorized to manage missions for mission null

Examples with other commands: 
_example for the command [product show]_
prosEO> product show abc
(E2802) User not logged in
(E2803) User null not authorized to manage products for mission null

_example for the command [productclass show]_
prosEO> productclass show
(E2802) User not logged in
(E2803) User null not authorized to manage product classes for mission null

_example for the command [productclass delete]_
prosEO> productclass delete abc
(E2802) User not logged in
(E2803) User null not authorized to manage product classes for mission null

_example for the command [productclass update]_
prosEO> productclass update abc
(E2802) User not logged in
(E2803) User null not authorized to manage product classes for mission null

Similar issues occur with the commands [orbit], [order] and [configuration]

**Comment by tangobravo62** [comment]
Fixed. "mission show" is allowed without login, and all other commands require prior login:
```
prosEO> mission show
---
- id: 59
  version: 1
  code: "ABC"
  name: null
  fileClasses:
  - "OPER"
  processingModes:
  - "OFFL"
  productFileTemplate: null
  spacecrafts:
[...]

prosEO> product show abc
(E2802) User not logged in
prosEO> productclass show
(E2802) User not logged in
prosEO> productclass delete abc
(E2802) User not logged in
prosEO> productclass update abc
(E2802) User not logged in
prosEO> 
```
