### ISSUE TITLE
[prosEO CLI] {product update} and {product delete} are terminating the CLI

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#29]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
The 2 commands [product delete] and [product update] are terminating the CLI.  They should have returned a message that the commands are not allowed while not terminating the CLI.

**Example outputs:**
prosEO> product delete
(E2802) User not logged in
prosEO Command Line Interface terminated by exception!

prosEO> product update
(E2802) User not logged in
prosEO Command Line Interface terminated by exception!

**Comment by tangobravo62** [comment]
Fixed:
```
prosEO> product delete
(E2802) User not logged in
prosEO> product update
(E2802) User not logged in
prosEO> 
```
