### ISSUE TITLE
[prosEO CLI] The error messages for the sub-commands of command order are not aligned

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#32]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
Executing the command [order update] returns a confusing error message, requesting a _product database ID_. Retrieving the help page mentions the parameter orderID that might be what the system is asking for but this is not very clear from a UX perspective as the user does not understand if this is indeed what is missing, or if there is another problem. On the contrary, order delete/approve/plan/release/suspend/resume/cancel/close/reset return an error message mentioning the orderID

**Example output:**
prosEO> order update
(E2802) User not logged in
(E2936) No product database ID given
prosEO> order update -h
(E2802) User not logged in
Update a processing order (only allowed in status initial)
Options:
    -f, --file        Path to file to read the order definition from
        --format      The file format (one of { JSON, XML, YAML }; default value JSON)
        --delete-attributes  Delete attributes not given in the order definition file and/or the command parameters
    -h, --help        Show help information for the current command level (top level commands, when called from the shell command line)
Positional parameters:
    orderId           The order identifier for user reference (mandatory if not read from file)
    attribute         An order attribute to update in the form "<attribute name>=<attribute value>", overrides values given in the order definition file
Subcommands:
prosEO> order update 123
(E2802) User not logged in
(E2803) User null not authorized to manage orders for mission null

**Comment by tangobravo62** [comment]
Fixed that commands could be run without login:
```
prosEO> order update
(E2802) User not logged in
prosEO> order update -h
(E2802) User not logged in
prosEO> order update 123
(E2802) User not logged in
prosEO> 
```

Fixed error message for "order update" command, now in line with "order update -h" help text; order update with a wrong order identifier returns an error message (after prior login):
```
prosEO> login S5P
Username (empty field cancels): proseo
Password for user proseo: 
(I2821) User proseo logged in

prosEO> order update
(E2936) No order identifier or database ID given

prosEO> order update -h
Update a processing order (only allowed in status initial)
Options:
    -f, --file        Path to file to read the order definition from
        --format      The file format (one of { JSON, XML, YAML }; default value JSON)
        --delete-attributes  Delete attributes not given in the order definition file and/or the command parameters
    -h, --help        Show help information for the current command level (top level commands, when called from the shell command line)
Positional parameters:
    orderId           The order identifier for user reference (mandatory if not read from file)
    attribute         An order attribute to update in the form "<attribute name>=<attribute value>", overrides values given in the order definition file
Subcommands:
    -- none --

prosEO> order update 123
(E2935) Order with identifier 123 not found
prosEO> 
```
