### ISSUE TITLE
"from" option in "order show" does not accept agreed time format

### ISSUE THREAD

**Issue by emelchinger** [dlr-eoc/prosEO#34]
More in detail: parsing of datetime results in Exception.

Example:
prosEO> login PTM
Username (empty field cancels): melchinger
Password for user melchinger:
(I2821) User melchinger logged in
prosEO> order show --from=2019-11-04T08:30:00
(E2925) prosEO Command Line Interface terminated by exception: Failed to execute CommandLineRunner

**Comment by tangobravo62** [comment]
Workaround: Use full date format with fractions of seconds and "Z" time zone:
```
prosEO> order show --from=2020-03-17T00:00:00.0Z
--- []

prosEO> 
```

Root cause: Exception from Instant.parse() not caught in OrderCommandRunner::showOrder().

**Comment by tangobravo62** [comment]
Handling of date/time values now more flexible throughout CLI:
```
prosEO> order show --from=2019-11-04T11:00+0200 --to=2019-11-05
---
- id: 81
  version: 2
  missionCode: "PTM"
  identifier: "L3_products_9:30-17:30"
  uuid: "e94eb21d-59a3-4b0a-bb5b-23cf0c0ed0cd"
  orderState: "PLANNED"
  executionTime: null
  startTime: "2019-11-04T09:30:00"
  stopTime: "2019-11-04T17:00:00"
[...]

prosEO> order show --from=2020-03-25T09:00:00.000000Z
---
- id: 80
  version: 1
  missionCode: "PTM"
  identifier: "L2_orbits_3000-3002"
  uuid: "30cd7870-3d8f-4e0f-bdf0-4bc8a90e33a5"
  orderState: "INITIAL"
  executionTime: null
  startTime: "2020-03-25T09:00:00"
  stopTime: "2020-03-25T14:03:30"
[...]
```
Allowable value formats now include:
- "2020-04-08"
- "2020-04-08GMT+02"
- "2020-04-08T11:30"
- "2020-04-08T11:30Z"
- "2020-04-08T11:30:45"
- "2020-04-08T11:30:45+02:00"
- "2020-04-08T11:30:45.123"
- "2020-04-08T11:30:45.123456-0200"

**Comment by tangobravo62** [comment]
Fix deployed on proseo.proseo-bcm.de
