### ISSUE TITLE
proseoCLI/OrderManager: "order approve ..." deletes at least requestedProductClasses

### ISSUE THREAD

**Issue by emelchinger** [dlr-eoc/prosEO#36]
The command "order approve <order identifier>" deletes at least requestedProductClasses.

Before:
requestedProductClasses:
  - "PTM_L2B"
  - "PTM_L2A"

After:
  requestedProductClasses: []

See complete output in attachment.

[approve.txt](https://github.com/dlr-eoc/prosEO/files/4360524/approve.txt)

**Comment by tangobravo62** [comment]
Fixed in commit c9a3c8c (updating of orders not fully implemented in OrderManager).

**Comment by tangobravo62** [comment]
@emelchinger Please verify and close if OK.

**Comment by tangobravo62** [comment]
Tested and OK.
