### ISSUE TITLE
[prosEO CLI] proseo command is illegal

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#4]
**Testing parameters**
User Login: no user login
Mission : no mission 

**Context**:
Executing the proseo command returns that the command is illegal.

**Output**:
prosEO> proseo
(E2916) Illegal command proseo

**Comment by tangobravo62** [comment]
The behaviour is correct, because "proseo" is not a command. It is the placeholder for the CLI executable in the help text. Clarified in the help text:

```
prosEO> help
Commands can be entered after the "prosEO>" command prompt. They can also be invoked on the shell command line 
following the name of the prosEO executable (e. g. "proseo") and at least one whitespace character.
[...]
So the general syntax is:
command [subcommand...] [option...] [parameter...]
```
