### ISSUE TITLE
RestOrder answer contents

### ISSUE THREAD

**Issue by emelchinger** [dlr-eoc/prosEO#41]
Correct display if requested orbits. 
There are multiple objects of same definition and gaps in orbit numbers are not supported.
Example:
"orbits" : [ {
    "spacecraftCode" : "PTS",
    "orbitNumberFrom" : 3000,
    "orbitNumberTo" : 3002
  }, {
    "spacecraftCode" : "PTS",
    "orbitNumberFrom" : 3000,
    "orbitNumberTo" : 3002
  }, {
    "spacecraftCode" : "PTS",
    "orbitNumberFrom" : 3000,
    "orbitNumberTo" : 3002
  } ],

**Comment by tangobravo62** [comment]
Generation of RestOrbitQuery objects fixed:
```
prosEO> order show
---
- id: 87
  version: 2
  missionCode: "PTM"
  identifier: "L2_orbits_3000-3002"
[...]
  orbits:
  - spacecraftCode: "PTS"
    orbitNumberFrom: 3000
    orbitNumberTo: 3002
[...]
```

@emelchinger Please verify and close if OK

**Comment by tangobravo62** [comment]
Tested and OK.
