### ISSUE TITLE
[prosEO CLI] Typing "-v" is executed without result or error message

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#5]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
Executing just "-v" does not return any error message or result.

**Output:**
prosEO> -v
prosEO>

**Further information:** 
Shouldn't typing -v alone return an output of some sort? If there is no version associated with proseo, then shouldn't the output/error message indicate this with a message similar to "no version was found", or,  'This option can only be used from a shell command line', as per the indication from the help page? Contrary to but relative to this, -u is taken as input and executes but because it is missing a username it fails. Shouldn't -v return something, along the same line of output? Example output:
prosEO> -u
(E2913) Illegal option value null for option user of type string

**Comment by tangobravo62** [comment]
Typing "-v" or "--version" now shows the version information:

```
prosEO> -v
prosEO Command Line Interface (v0.1.0)
prosEO> --version
prosEO Command Line Interface (v0.1.0)
```

However, this is not syntactically correct (strictly speaking), "-v" is just meant as a program invocation parameter, not as a standalone command.

TODO: Make "-v", "--version", "-h" and "--help" illegal as standalone commands.

**Comment by dlr-tangosierra** [comment]
In the latest version of the command line interface this is the output:
prosEO> -v
(E2912) Option -v not allowed for command proseo

As such, it is completed as per the "TODO" from the previous comment.

#

On the other hand, "-h" and "--help" still function.

# 

--version is also functioning but it might be a helpful for the users of prosEO, e.g. in case of a bug the users can easily find which version they are using. Can it be added as a feature?

**Comment by tangobravo62** [comment]
Note that the option for showing the version has changed to uppercase V:
```
prosEO (PTM)> -v
(E2912) Option -v not allowed for command proseo
prosEO (PTM)> -V
prosEO Command Line Interface (v0.1.0)
prosEO (PTM)> --version
prosEO Command Line Interface (v0.1.0)
```
In line with the comment above by dlr-tangosierra the standalone options `-V`, `--version`, `-h` and `--help` remain valid inputs, although not strictly covered by the command syntax (note however that calling e. g. `<prosEO executable> --version` on the shell command line is officially supported).
