### ISSUE TITLE
Handle cycles in selection rules

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#54]
It is allowed to have cyclic dependencies in selection rules (e. g. background correction in Sentinel-5 UPAS). Currently this would lead to an infinite loop of job steps being generated:

Sentinel-5P uses so-called "background correction" products. Let `BGC_CLOUD` be the background correction product (usually calculated per calendar day) for `L2__CLOUD` products (usually calculated per orbit), then the selection rules are:
- `L2__CLOUD: FOR BGC_CLOUD SELECT ValIntersect(1d, 0d); FOR L1B SELECT LatestValCover(0, 0)`
- `BGC_CLOUD: FOR L2__CLOUD SELECT ValIntersect(1d, 0d) MINCOVER 45; FOR BGC_CLOUD SELECT ValIntersect(1d, 0d)`

The Production Planner shall detect loops and stop generating job steps, if during recursion the same product class is encountered a second time.

**Comment by tangobravo62** [comment]
To be checked: Since the planner in the case above would in theory produce infinite loops over the same products, the fact that the planner actually does not generate new job steps, if the product in question is already produced by another job step of the same job, the situation above may not really be a problem.

Todo: Design loop example and test it.

**Comment by emelchinger** [comment]
Loop example attached, first test was successful.
[test.zip](https://github.com/dlr-eoc/prosEO/files/4894821/test.zip)
