### ISSUE TITLE
Store job order file in job step

### ISSUE THREAD

**Issue by emelchinger** [dlr-eoc/prosEO#64]
Store the generated job order file in job step as file name reference or as blob with complete content 
(used for analysis of failed processors)

**Comment by tangobravo62** [comment]
Discussion 2020-06-22: Job Order file name (as delivered by Storage Manager) is stored in the job step. When the job step is deleted, the Job Order file shall be deleted from the Storage Manager.

**Comment by emelchinger** [comment]
Implemented.

**Comment by tangobravo62** [comment]
Implemented:
<img width="1494" alt="Bildschirmfoto 2021-04-28 um 15 04 11" src="https://user-images.githubusercontent.com/29191859/116408475-21df1a80-a833-11eb-95fb-c3a066c40a95.png">
