### ISSUE TITLE
[prosEO CLI] UX: Typing [space]help results in an error message with no indication of what the problem is

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#7]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
Typing [space]help results in an error message with no indication of what the problem is. On the contrary, help[space] functions. The same issue is occuring for all other commands. 

**Example output:**
prosEO>  help
(E2916) Illegal command
prosEO> help
Commands can be invoked...

**Enhancement:**
Typing [space]help functions. This could be an enhancement to the user experience as this is a functionality already in place in internet search engines, for example.

**Comment by tangobravo62** [comment]
Fixed:

```
prosEO>  logout
(I2823) User null logged out
prosEO>       help      
Commands can be invoked on the shell command line ...
```
