### ISSUE TITLE
Planner does not receive job log from Kubernetes (high load?)

### ISSUE THREAD

**Issue by tangobravo62** [dlr-eoc/prosEO#79]
During the S2 test campaign the Production Planner did not receive logs from Kubernetes for successful jobs:
```
prosEO (S2)> job step show -v 247
---
id: 248
version: 4
name: "proseojob248"
jobId: 247
jobStepState: "COMPLETED"
outputParameters: []
processingMode: "generate_datastrip"
inputProductClasses:
- "L1C_DS"
outputProductClass: "L2A_DS"
processingStartTime: "2020-06-23T16:33:15"
processingCompletionTime: "2020-06-23T16:33:34"
stdoutLogLevel: "INFO"
stderrLogLevel: "INFO"
processingStdOut: null
processingStdErr: null
```
To be checked whether this could have been due to high load conditions? (Many orders were generated in a short sequence.)

**Comment by tangobravo62** [comment]
A similar issue was observed for Sentinel-5P where long-running job steps did not receive the job step log until after completion. An example is shown in the attached screenshot.

<img width="1209" alt="Bildschirmfoto 2021-05-25 um 16 41 15" src="https://user-images.githubusercontent.com/29191859/119525600-ecb8e000-bd7e-11eb-9fe7-eef5eea3ddb7.png">

**Comment by katharinabassler** [comment]
Issue has been resolved for GUI, but potentially not for CLI.

**Comment by tangobravo62** [comment]
Not relevant for CLI. Issue closed.
