### ISSUE TITLE
[prosEO CLI] UX: A command similar to 'clear' could prove useful

### ISSUE THREAD

**Issue by dlr-tangosierra** [dlr-eoc/prosEO#8]
**Testing parameters:**
User Login: no user login
Mission : no mission

**Context:**
The user needs to use the ENTER button several times in order to have some space between outputs/texts. This might be a good addition from the UX point of view.

**Comment by tangobravo62** [comment]
What is intended here? A function which clears the screen and returns with a single command prompt on the top of the screen?

**Comment by dlr-tangosierra** [comment]
Yes, a function like what you describe could be a welcome addition.

**Comment by tangobravo62** [comment]
Implementation hints:
https://stackoverflow.com/questions/2979383/java-clear-the-console

**Comment by tangobravo62** [comment]
Implemented with commit 835b9a3.

**Comment by tangobravo62** [comment]
Tested and OK.
